### ISSUE TITLE
ocean.js API reference is broken

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#632] opened 2021-05-04 11:04 UTC
**Describe the bug**
Go to https://docs.oceanprotocol.com/references/ocean.js

And it only says "JavaScript client library for Ocean Protocol".

It should have all the docs stuff. It _was_ working 1-2 weeks ago when I was last there

**Comment by kremalicious** [comment] 2021-05-04 11:08
duplicate of #527

**Closed by kremalicious** 2021-05-04 11:08 UTC
Labels: bug

**Comment by akshay-ap** [comment] 2021-05-04 14:26
On adding some debug logs, I found that `cleanData` is empty array. https://github.com/oceanprotocol/docs/blob/5bd24c5be3195b1eda7923570ac63047d463943b/src/templates/Typedoc/utils.js#L25 

There is a change in typedoc-generated json.
@kremalicious Thanks for sharing the pr: https://github.com/oceanprotocol/docs/pull/546.
