### ISSUE TITLE
Define user-input object used in "Parameters to C2D" in Ocean.js

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#885] opened 2022-02-13 08:01 UTC
Macro context:
- Overall goal: "User input data required for assets & algorithms" [multi-repo #106](https://github.com/oceanprotocol/multi-repo-issue/issues/106) 
- We already have this in the backend (ocean.js/py/provider/c2d)
- Now the aim is to get it into the frontend (Ocean Market): "First-class integration with Parameters to C2D in Ocean Market". This what Corrie / mPowered will build, as described in their R14 OceanDAO [grant proposal](https://port.oceanprotocol.com/t/first-class-integration-with-parameters-to-c2d-in-ocean-market/1421). They have had many iterations with @alexcos20 already.

The aim of _this_ issue is:
- Define the object that users input. Which has the definition for services & algos
- Update documentation accordingly. 

**More background**

(trentmc) The goals of this make sense, I've been tracking this a long time. Anyone using C2D for any real work needs this yesterday, we keep getting the same feedback (DataUnion, Algovera, mPowered, etc). So if we want C2D to be truly useful, we need this.

**Comment by trentmc** [comment] 2022-02-13 08:03
PR is at: https://github.com/oceanprotocol/docs/pull/882

**Comment by AnaLoznianu** [comment] 2022-07-05 11:04
Closing this as a duplicate of #947

**Closed** 2022-07-05 11:04 UTC
Labels: Type: Enhancement, Priority: Low
